### ISSUE TITLE
Suggestion: Looping resolution

### ISSUE THREAD

**Issue by Alby1987** [graphhopper/map-matching#1]
Hi! I've read about the loop problem, and your idea about MappointX, MappointX+4, etc... I was thinking it would be better to divide the subtrack based on same points. For example 
![idea1](https://cloud.githubusercontent.com/assets/8544258/5441264/5c28217e-848f-11e4-9e73-091191403d1c.png) instead of routing from A to B, you can route in pair A-B,C-D,etc...

If points are near (5m-10m-adjustable) and subsequent, treat them as one. In are near but not subsequent, like the drawing above, dividing the route should be OK. It's a good idea? :)

**Comment by karussell** [comment]
I'm currently investigating this and a loop detection is possible (real distance versus found distance), so that one has to do the search recursivly until no (big) loop is found. As this approach is a bit more complex and possibly also slower I will do the heuristical splitting into sub-tracks for now as a fix.

**Comment by karussell** [comment]
BTW: the work for this is done in the issue_1 branch

**Comment by chrissssss** [comment]
Hi! Good work, results are far better than before! I'm sorry, but I've tested master half an hour ago with the following http://www.gpsies.com/map.do?fileId=dcnjvydxcmwcpgoq  on a small dataset around Berlin DGZ Ring with foot encoder. 
The check fails at doWork(), but even if I comment it out it the result is strange.

Would you have a look? http://www.gpsies.com/map.do?fileId=ypzywwdattpetvdc 

The upper loop seems to be missing.

**Comment by karussell** [comment]
> with the following http://www.gpsies.com/map.do?fileId=dcnjvydxcmwcpgoq

I get: "Diese Strecke ist nicht öffentlich und wurde noch nicht von chrissssss freigegeben."

>  The check fails at doWork(), but even if I comment it out it the result is strange.

Yeah, if the check passes the results should be reasonable.

> Just created a pull request to hand you over the junit test-stub

That is very helpful! In case when I cannot reproduce it in my test area (leipzig) can I include the data set and test you provided under the Apache License?

For now the looping issue is solved via partitioning the route into smaller parts, which solves this very pragmatically but still gives strange results at the merge location. And you have to provide the distance to do the split (separatedSearchDistance). In a later improvement the split could be done for the loop crossing (and one or two additional via points), but we need a proper loop detection and of course a 100% working simple solution before.

**Comment by chrissssss** [comment]
Hi Peter,
the unit test already has your header included. The graph data is taken from OSM and the gpx you can do what you want with ;) 
I'll give you a glance at what the gpx looks like
![bildschirmfoto 2015-02-08 um 08 53 53](https://cloud.githubusercontent.com/assets/1689940/6163569/7fcb5b2c-b294-11e4-8a78-5515f166c475.png)
It's included in the Unit-Test

**Comment by karussell** [comment]
> the unit test already has your header included

ok, just wanted to make it sure :)

If you decrease the search distance you get a good looking match:
```java
MapMatching mapMatching = new MapMatching(graph, locationIndex, encoder);
mapMatching.setSeparatedSearchDistance(100);
```

Still I have a look into the problem: check method saying dup edge for the default distance

**Comment by karussell** [comment]
Okay, the duplicate edge is because of the beginning of the second loop is stored and the second search already finds GPS points back to the destination => the small beginning of Wilhem-Wagnenfeld-Straße is stored twice (u-turn). Currently we have to live with workarounds until a more solid solution is implemented (I know how, but would take me too much time). The workaround is to decrease the separatedSearchDistance OR to accept that sometimes loops are ignored and you specify a new forceRepair=true parameter.
