### ISSUE TITLE
 Problem with file .\track-data\*.gpx Error: Cannot find matching path! Wrong vehicle car or missing OpenStreetMap data? Try to increase maxSearchMultiplier

### ISSUE THREAD

**Issue by ObadaM** [graphhopper/map-matching#26]
Hello,

I installed the map-matching some days ago and i'm trying to run it on different GPX files of GPS bike data. Some of them work and i get good results some others don't and i'm getting the following error: 
"Problem with file .\track-data\*.gpx Error: Cannot find matching path! Wrong vehicle car or missing OpenStreetMap data? Try to increase maxSearchMultiplier=100.0"

Even though i set my vehicle to be a bike.
I tried to set the maxSearchMultiplier to 100.0 and it didn't work.
I don't know whats wrong and i couldn't debug the whole algorithm.

Is there any restrictions on the GPX files? Am i missing something here?

Thanks for your help.

**Comment by ratrun** [comment]
In my branch I translated this log into "Check missing OpenStreetMap data". Anyhow, first I would try to set maxSearchMultiplier up to 800.
In case that you speak German you might read up https://github.com/ratrun/map-matching/blob/htmlresultoutput/htmlreport.de.md. If this does not help you please post your GPX. Without a GPX it is next to impossible to guess what might be the reason for your case.

**Comment by ObadaM** [comment]
Thanks for your reply.
I tried the maxSearchMultiplier it didn't work as well and unfortunately i don't know much of German, please have a look on the GPX file:
https://www.dropbox.com/s/hx8lz1kfbx4qqr6/trace2ClearGPX22.gpx?dl=0

**Comment by ratrun** [comment]
Your example works for me using the latest Saarland geofabrik extract, vehicle car and following settings:

gpxAccuracy=15 graph.flagEncoders=car forceRepair=true separatedSearchDistance=250 htmlReport=true maxSearchMultiplier=100

I guess that you are using an OSM input file which does not cover your area. This will generate the oberserved error:  "Error: Cannot find matching path! Wrong vehicle car or missing OpenStreetMap data?"

Note: From the beginning of the input GPX in the south of "Prinzenweiher", it looks as if the track was recorded using vehicle=foot, because there are only foothpaths mapped there. As the detour to the Meerwiesertalweg in the north is not too far away, the algorithm snaps in to this segment.

**Comment by karussell** [comment]
Thanks @ratrun ! @ObadaM maybe you need to remove the graph-cache as your current vehicle is also not the one you specified

**Comment by ObadaM** [comment]
Thanks @ratrun i've downloaded the latest Saarland.osm.pbf and with these parameters now it works!
