### ISSUE TITLE
Investigate performance slow down

### ISSUE THREAD

**Issue by karussell** [graphhopper/map-matching#97]
There [seems to be a problem](https://discuss.graphhopper.com/t/use-the-new-hybrid-mode-for-map-matching/2003/5) with speed since the u-turn avoidance.

**Comment by stefanholder** [comment]
As discussed [here](https://github.com/graphhopper/map-matching/pull/88#issuecomment-269808635) u-turn avoidance should cause at most a 4x slowdown (at most double number of candidates means at most 4 times number of transitions). But since some candidates are tower nodes and query results are deduped (#91) the slowdown should be less than 4x. Actually, @kodonnell only measured a 2.5x slowdown after u-turn avoidance was implemented (see first link), which was even before #91.

**Comment by michaz** [comment]
You gave the answer in #80. When I run ``Measurement`` and set the initial collection size to ``150_000``, which will happen in large graphs, map matching takes forever, because it allocates and deallocates 600k a zillion times.

**Comment by karussell** [comment]
Oh, ugly. Thanks a lot @michaz - this got lost in issues :( !

Should we make initial collection size configurable in GH core or should we use a better heuristic like small initial size for small beeline distance? Also Dijstra and A* should have a different initialization, plus the different initialization size for bidirectional vs. unidirectional looks unsynched (Dijkstra 2K vs. 150K for bidir Dijkstra).

**Comment by michaz** [comment]
I think in library code one should not add a special assumption, an overridden method, or even a configuration parameter, anywhere, for a 10% speed-up. You would probably overfit it to the particular case you are looking at, plus you make the code bad.

Except maybe the authors of the JVM, because then half the world gets 10% faster, and the investment pays off.

Look at the formula for the initial collection size (I had to set a breakpoint to understand where the value actually comes from, because it goes back and forth so often between super and subclasses):

It is almost evil, because the typical graph size is "the world", or "a country", except in toy scenarios and test cases. So the result of the formula is almost always 150000, except in toy scenarios and test cases, so you never find a problem with that.

We'll probably meet in the middle, but you were asking: I would remove all of it.

**Comment by michaz** [comment]
``Math.min(Math.max(200, graph.getNodes() / 10), 150_000)``

Also, if we must use a formula: I think we are looking for the expected length of a path, as a function of graph size. Shouldn't that be something with a logarithm in it?

For example: Say I mostly compute urban walk paths. What does the expected path length have to do with whether I imported Barcelona, or the whole world? Not a lot, either way, I am still computing urban walk paths. The only point where the graph size comes in is that I _can't_ compute more than an urban walk path if I only imported a city.

Sounds like something with a logarithm. :)
